version: '3.9'

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER : user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
